# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
critical:
    - '(critical|urgent)'
enhancement:
    - '(Create|Improve|Include|generate|Implement|should|Should)'
bug:
    - '(not working|Not showing|Issue|bug|error|shouldn)'
documentation:
    - '(schematic|folder|documentation)'
