# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
critical:
    - '(critical|urgent)'
enhancement:
    - '(create|improve|include|generate)'
bug:
    - '(not working|not showing|issue)'
action:
    - '(action)'
