# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
critical:
    - '(critical|urgent)'
enhancement:
    - '(create|improve|include|generate|implement)'
bug:
    - '(not working|not showing|issue|bug|error)'
documentation:
    - '(schematic|folder|documentation)'
